//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivedStudent
    {
        [Key]
        public int ArchivedStudent_Id { get; set; }
        public string admission_No { get; set; }
        public string class_roll_No { get; set; }
        public Nullable<System.DateTime> admission_date { get; set; }
        public string First_Name { get; set; }
        public string Midle_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string gender { get; set; }
        public string blood_group { get; set; }
        public string birth_place { get; set; }
        public string C_language { get; set; }
        public string religion { get; set; }
        public string nationality { get; set; }
        public string C_state { get; set; }
        public string city { get; set; }
        public string address_1 { get; set; }
        public string address_2 { get; set; }
        public string pin_code { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string email_id { get; set; }
        public string photo_filename { get; set; }
        public string photo_content_type { get; set; }
        public byte[] photo_data { get; set; }
        public int photo_file_size { get; set; }
        public string status_descripton { get; set; }
        public bool is_active { get; set; }
        public bool is_deleted { get; set; }
        public bool is_sms_enabled { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int Fk_Former_Id { get; set; }
        public int Fk_Batch_id { get; set; }
        public int Fk_Country_id { get; set; }
        public int Fk_Student_Category_id { get; set; }
        public int Fk_Immidiate_Contact_id { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual StudentCategory StudentCategory { get; set; }
    }
}
