//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public Batch()
        {
            this.ArchivedStudents = new HashSet<ArchivedStudent>();
            this.AssessmentScores = new HashSet<AssessmentScore>();
            this.Attendences = new HashSet<Attendence>();
            this.CceReports = new HashSet<CceReport>();
            this.ClassTimings = new HashSet<ClassTiming>();
            this.ExamGroups = new HashSet<ExamGroup>();
            this.GradingLevels = new HashSet<GradingLevel>();
            this.Students = new HashSet<Student>();
            this.StudentSubjects = new HashSet<StudentSubject>();
            this.SubjectLeaves = new HashSet<SubjectLeave>();
            this.Subjects = new HashSet<Subject>();
            this.TimetableEntries = new HashSet<TimetableEntry>();
            this.Week_Day = new HashSet<Week_Day>();
        }
    [Key]
        public int Batch_id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> C_start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public bool is_deleted { get; set; }
        public int Fk_Course_id { get; set; }
        public int Fk_Employee_id { get; set; }
    
        public virtual ICollection<ArchivedStudent> ArchivedStudents { get; set; }
        public virtual ICollection<AssessmentScore> AssessmentScores { get; set; }
        public virtual ICollection<Attendence> Attendences { get; set; }
        public virtual Course Course { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<CceReport> CceReports { get; set; }
        public virtual ICollection<ClassTiming> ClassTimings { get; set; }
        public virtual ICollection<ExamGroup> ExamGroups { get; set; }
        public virtual ICollection<GradingLevel> GradingLevels { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<StudentSubject> StudentSubjects { get; set; }
        public virtual ICollection<SubjectLeave> SubjectLeaves { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
        public virtual ICollection<TimetableEntry> TimetableEntries { get; set; }
        public virtual ICollection<Week_Day> Week_Day { get; set; }
    }
}
