//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CceExamCategory
    {
        public CceExamCategory()
        {
            this.CceWeightages = new HashSet<CceWeightage>();
            this.ExamGroups = new HashSet<ExamGroup>();
            this.FaGroups = new HashSet<FaGroup>();
        }
    [Key]
        public int Cce_Exam_Category_id { get; set; }
        public string Name { get; set; }
        public string desc_ { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<CceWeightage> CceWeightages { get; set; }
        public virtual ICollection<ExamGroup> ExamGroups { get; set; }
        public virtual ICollection<FaGroup> FaGroups { get; set; }
    }
}
