//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CceGrade
    {
        [Key]
        public int Cce_Grade_id { get; set; }
        public string Name { get; set; }
        public double grade_point { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int Fk_Cce_Grade_Set_id { get; set; }
    
        public virtual CceGradeSet CceGradeSet { get; set; }
    }
}
