//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CceGradeSet
    {
        public CceGradeSet()
        {
            this.CceGrades = new HashSet<CceGrade>();
            this.FaGroups = new HashSet<FaGroup>();
            this.ObservationGroups = new HashSet<ObservationGroup>();
        }
    [Key]
        public int Cce_Grade_Set_id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<CceGrade> CceGrades { get; set; }
        public virtual ICollection<FaGroup> FaGroups { get; set; }
        public virtual ICollection<ObservationGroup> ObservationGroups { get; set; }
    }
}
