//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CceReport
    {
        [Key]
        public int Cce_Reports_id { get; set; }
        public string observable_type { get; set; }
        public string grade_string { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int FK_Student_id { get; set; }
        public int Fk_Observable_id { get; set; }
        public int Fk_Batch_id { get; set; }
        public int Fk_Exam_id { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Exam Exam { get; set; }
        public virtual Observation Observation { get; set; }
        public virtual Student Student { get; set; }
    }
}
