//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CceWeightage
    {
        public CceWeightage()
        {
            this.CceWeightagesCourses = new HashSet<CceWeightagesCourse>();
        }
    [Key]
        public int Cce_Weightage_id { get; set; }
        public int weightage { get; set; }
        public string criteria_type { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int Fk_Cce_Exam_Category_id { get; set; }
    
        public virtual CceExamCategory CceExamCategory { get; set; }
        public virtual ICollection<CceWeightagesCourse> CceWeightagesCourses { get; set; }
    }
}
