//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CceWeightagesCourse
    {
        [Key]
        public int Cce_Weightages_Course_id { get; set; }
        public int Fk_Cce_Weightage_id { get; set; }
        public int Fk_Course_id { get; set; }
    
        public virtual CceWeightage CceWeightage { get; set; }
        public virtual Course Course { get; set; }
    }
}
