//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassTiming
    {
        public ClassTiming()
        {
            this.SubjectLeaves = new HashSet<SubjectLeave>();
            this.TimetableEntries = new HashSet<TimetableEntry>();
        }
    [Key]
        public int Class_Timing_id { get; set; }
        public string Name { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
        public bool is_break { get; set; }
        public bool is_deleted { get; set; }
        public int Fk_Batch_id { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual ICollection<SubjectLeave> SubjectLeaves { get; set; }
        public virtual ICollection<TimetableEntry> TimetableEntries { get; set; }
    }
}
