//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Batches = new HashSet<Batch>();
            this.CceWeightagesCourses = new HashSet<CceWeightagesCourse>();
            this.ClassDesignations = new HashSet<ClassDesignation>();
            this.RankingLevels = new HashSet<RankingLevel>();
        }
    [Key]
        public int Course_id { get; set; }
        public string course_name { get; set; }
        public string code { get; set; }
        public string section_name { get; set; }
        public bool is_deleted { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string grading_type { get; set; }
    
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual ICollection<CceWeightagesCourse> CceWeightagesCourses { get; set; }
        public virtual ICollection<ClassDesignation> ClassDesignations { get; set; }
        public virtual ICollection<RankingLevel> RankingLevels { get; set; }
    }
}
