//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePreviousData
    {
        [Key]
        public int Previous_Data_id { get; set; }
        public int Fk_Employee_Id { get; set; }
        public string institution { get; set; }
        public string year { get; set; }
        public string course { get; set; }
        public double total_mark { get; set; }
        public int Fk_Certificate_Id { get; set; }
    }
}
