//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeave
    {
        [Key]
        public int Employee_Leave_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<decimal> leave_count { get; set; }
        public Nullable<decimal> leave_taken { get; set; }
        public Nullable<System.DateTime> reset_date { get; set; }
        public int Fk_Employee_id { get; set; }
        public int Fk_Employee_Leave_Type_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EmployeeLeaveType EmployeeLeaveType { get; set; }
    }
}
