//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDepartmentEvent
    {
        [Key]
        public int Employee_Department_Event_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int Fk_Event_id { get; set; }
        public int Fk_Employee_Department_id { get; set; }
    
        public virtual EmployeeDepartment EmployeeDepartment { get; set; }
        public virtual Event Event { get; set; }
    }
}
