//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttendence
    {
        [Key]
        public int Employee_Attendences_id { get; set; }
        public Nullable<System.DateTime> attendence_date { get; set; }
        public string reason { get; set; }
        public bool is_half_day { get; set; }
        public int Fk_Employee_id { get; set; }
        public int Fk_Employee_Leave_Type_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EmployeeLeaveType EmployeeLeaveType { get; set; }
    }
}
