//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAdditionalField
    {
        public EmployeeAdditionalField()
        {
            this.EmployeeAdditionalDetails = new HashSet<EmployeeAdditionalDetail>();
        }
    [Key]
        public int Additional_Field_id { get; set; }
        public string Name { get; set; }
        public bool status_ { get; set; }
    
        public virtual ICollection<EmployeeAdditionalDetail> EmployeeAdditionalDetails { get; set; }
    }
}
