//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDepartment
    {
        public EmployeeDepartment()
        {
            this.ArchivedEmployees = new HashSet<ArchivedEmployee>();
            this.Employees = new HashSet<Employee>();
            this.EmployeeDepartmentEvents = new HashSet<EmployeeDepartmentEvent>();
        }
    [Key]
        public int Employee_Department_id { get; set; }
        public string code { get; set; }
        public string Name { get; set; }
        public bool status_ { get; set; }
    
        public virtual ICollection<ArchivedEmployee> ArchivedEmployees { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<EmployeeDepartmentEvent> EmployeeDepartmentEvents { get; set; }
    }
}
