//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    [Bind(Exclude = "Id")]
    public partial class EmployeeDepartment
    {
        public EmployeeDepartment()
        {
            this.ArchivedEmployees = new HashSet<ArchivedEmployee>();
            this.Employees = new HashSet<Employee>();
            this.EmployeeDepartmentEvents = new HashSet<EmployeeDepartmentEvent>();
        }
        [Key,DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [ScaffoldColumn(false)]
        public int Id { get; set; }

        [DisplayName("Deptt. Code")]
        public string code { get; set; }

        [DisplayName("Deptt. Name")]
        public string Name { get; set; }

        [DisplayName("Deptt. Status")]
        public bool status_ { get; set; }
    
        public virtual ICollection<ArchivedEmployee> ArchivedEmployees { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<EmployeeDepartmentEvent> EmployeeDepartmentEvents { get; set; }
    }
}
