//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeResearch
    {
        [Key]
        public int Id { get; set; }
        public string value { get; set; }
        public int Fk_Employee_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
