//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    [Bind(Exclude = "Id")]
    public partial class Event
    {
        public Event()
        {
            this.EmployeeDepartmentEvents = new HashSet<EmployeeDepartmentEvent>();
            this.Exams = new HashSet<Exam>();
        }
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [ScaffoldColumn(false)]
        public int Id { get; set; }

        [DisplayName("Title")]
        public string title { get; set; }

        [DisplayName("Description")]
        public string desc_ { get; set; }

        [DisplayName("Start Date")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> start_date_ { get; set; }

        [DisplayName("End Date")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> end_date { get; set; }

        [DisplayName("For Whome")]
        public bool is_common { get; set; }

        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> created_at { get; set; }
        public string Fk_Origin_id { get; set; }
        
        public virtual ApplicationUser User { get; set; }
        public virtual ICollection<EmployeeDepartmentEvent> EmployeeDepartmentEvents { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
    }
}
