//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EmployeeDepartmentEvents = new HashSet<EmployeeDepartmentEvent>();
            this.Exams = new HashSet<Exam>();
        }
    [Key]
        public int Event_id { get; set; }
        public string title { get; set; }
        public string desc_ { get; set; }
        public Nullable<System.DateTime> start_date_ { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public bool is_common { get; set; }
        public bool is_holiday { get; set; }
        public bool is_exam { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public bool is_due { get; set; }
        public int Fk_Origin_id { get; set; }
        public string origin_type { get; set; }
    
        public virtual ICollection<EmployeeDepartmentEvent> EmployeeDepartmentEvents { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
    }
}
