//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamGroup
    {
        public ExamGroup()
        {
            this.Exams = new HashSet<Exam>();
        }
    [Key]
        public int Exam_Group_id { get; set; }
        public string Name { get; set; }
        public string exam_type { get; set; }
        public bool is_published { get; set; }
        public bool result_published { get; set; }
        public Nullable<System.DateTime> exam_date { get; set; }
        public bool is_final_exam { get; set; }
        public int Fk_Cce_Exam_Category_id { get; set; }
        public int Fk_Batch_id { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual CceExamCategory CceExamCategory { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
    }
}
