//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public Exam()
        {
            this.AssessmentScores = new HashSet<AssessmentScore>();
            this.CceReports = new HashSet<CceReport>();
            this.ExamScores = new HashSet<ExamScore>();
        }
    [Key]
        public int Exam_id { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public int maximum_marks { get; set; }
        public int minimum_marks { get; set; }
        public int weightage { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int Fk_Exam_Group_id { get; set; }
        public int Fk_Subject_id { get; set; }
        public int Fk_Grading_Level_id { get; set; }
        public int Fk_Event_id { get; set; }
    
        public virtual ICollection<AssessmentScore> AssessmentScores { get; set; }
        public virtual ICollection<CceReport> CceReports { get; set; }
        public virtual Event Event { get; set; }
        public virtual ExamGroup ExamGroup { get; set; }
        public virtual GradingLevel GradingLevel { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<ExamScore> ExamScores { get; set; }
    }
}
