//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaCriteria
    {
        [Key]
        public int Fa_Criterias_id { get; set; }
        public string fa_Name { get; set; }
        public string desc_ { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int sort_order { get; set; }
        public bool is_deleted { get; set; }
        public int Fk_Fa_Group_id { get; set; }
    
        public virtual FaGroup FaGroup { get; set; }
    }
}
