//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaGroup
    {
        public FaGroup()
        {
            this.FaCriterias = new HashSet<FaCriteria>();
            this.FaGroupsSubjects = new HashSet<FaGroupsSubject>();
        }
    [Key]
        public int Fa_Group_id { get; set; }
        public string Name { get; set; }
        public string desc_ { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public double max_marks { get; set; }
        public bool is_deleted { get; set; }
        public int Fk_Cce_Exam_Category_id { get; set; }
        public int Fk_Cce_Grade_Set_id { get; set; }
    
        public virtual CceExamCategory CceExamCategory { get; set; }
        public virtual CceGradeSet CceGradeSet { get; set; }
        public virtual ICollection<FaCriteria> FaCriterias { get; set; }
        public virtual ICollection<FaGroupsSubject> FaGroupsSubjects { get; set; }
    }
}
