//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gardian
    {
        [Key]
        public int Gardian_id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string relation { get; set; }
        public string email_id { get; set; }
        public string office_phone1 { get; set; }
        public string office_phone2 { get; set; }
        public string mobile_phone { get; set; }
        public string office_address_line1 { get; set; }
        public string office_address_line2 { get; set; }
        public string city { get; set; }
        public string C_state { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string occupation { get; set; }
        public double income { get; set; }
        public string education { get; set; }
        public Nullable<System.DateTime> reated_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int Fk_Country_id { get; set; }
        public int Fk_User_Id { get; set; }
        public int Fk_Student_Id { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
