//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    [Bind(Exclude = "Id")]
    public partial class Job
    {
        [Key,DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [ScaffoldColumn(false)]
        public int Id { get; set; }

        [DisplayName("Title")]
        public string title { get; set; }
        
        [DisplayName("Description")]
        public string desc_ { get; set; }
        
        [DisplayName("Job Reference")]
        public string job_ref { get; set; }
        
        [DisplayName("Department")]
        public string department { get; set; }
        
        [DisplayName("Location")]
        public string location { get; set; }
        
        [DisplayName("Minimum Salary")]
        public int min_salary { get; set; }
        
        [DisplayName("Maximum Salary")]
        public int max_salary { get; set; }

        [DisplayName("Job Type")]
        public int hours { get; set; }

        public Nullable<System.DateTime> created_date { get; set; }
        
        [DisplayName("Application Form")]
        public string application_form { get; set; }
        
        [DisplayName("Email To Apply")]
        public string email_to_apply { get; set; }
    }
}
