//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityUniversityPortal.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [Key]
        public int job_id { get; set; }
        public string desc_ { get; set; }
        public string title { get; set; }
        public string job_ref { get; set; }
        public string department { get; set; }
        public string location { get; set; }
        public int min_salary { get; set; }
        public int max_salary { get; set; }
        public string hours { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string application_form { get; set; }
        public string email_to_apply { get; set; }
    }
}
