//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Observation
    {
        public Observation()
        {
            this.CceReports = new HashSet<CceReport>();
        }
    [Key]
        public int Observation_id { get; set; }
        public string Name { get; set; }
        public string desc_ { get; set; }
        public bool is_active { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int sort_order { get; set; }
        public int Fk_Observation_Group_id { get; set; }
    
        public virtual ICollection<CceReport> CceReports { get; set; }
        public virtual ObservationGroup ObservationGroup { get; set; }
    }
}
