//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObservationGroup
    {
        public ObservationGroup()
        {
            this.Observations = new HashSet<Observation>();
        }
    [Key]
        public int Observation_Group_id { get; set; }
        public string Name { get; set; }
        public string header_name { get; set; }
        public string desc_ { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string Observation_kind { get; set; }
        public double max_marks { get; set; }
        public bool is_deleted { get; set; }
        public int Fk_Cce_Grade_Set_id { get; set; }
    
        public virtual CceGradeSet CceGradeSet { get; set; }
        public virtual ICollection<Observation> Observations { get; set; }
    }
}
