//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankingLevel
    {
        [Key]
        public int Ranking_Level_id { get; set; }
        public string Name { get; set; }
        public decimal gpa { get; set; }
        public decimal marks { get; set; }
        public int subject_count { get; set; }
        public int priority { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public bool full_course { get; set; }
        public string subject_limit_type { get; set; }
        public string marks_limit_type { get; set; }
        public int Fk_Course_id { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
