//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAdditionalDetail
    {
        [Key]
        public int Additional_Detail_id { get; set; }
        public int Fk_Student_Id { get; set; }
        public int Fk_Additional_Field_id { get; set; }
        public string additional_info { get; set; }
    
        public virtual StudentAdditionalField StudentAdditionalField { get; set; }
        public virtual Student Student { get; set; }
    }
}
