//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCategory
    {
        public StudentCategory()
        {
            this.ArchivedStudents = new HashSet<ArchivedStudent>();
            this.Students = new HashSet<Student>();
        }
    [Key]
        public int Student_Category_id { get; set; }
        public string Name { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual ICollection<ArchivedStudent> ArchivedStudents { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
