//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSubject
    {
        [Key]
        public int Student_Subject_id { get; set; }
        public int Fk_Subject_id { get; set; }
        public int Fk_Student_id { get; set; }
        public int Fk_Batch_id { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Student Student { get; set; }
    }
}
