//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAdditionalField
    {
        public StudentAdditionalField()
        {
            this.StudentAdditionalDetails = new HashSet<StudentAdditionalDetail>();
        }
    [Key]
        public int Additional_Field_id { get; set; }
        public string Name { get; set; }
        public bool C_status { get; set; }
    
        public virtual ICollection<StudentAdditionalDetail> StudentAdditionalDetails { get; set; }
    }
}
