//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.EmployeesSubjects = new HashSet<EmployeesSubject>();
            this.Exams = new HashSet<Exam>();
            this.FaGroupsSubjects = new HashSet<FaGroupsSubject>();
            this.SubjectLeaves = new HashSet<SubjectLeave>();
            this.TimetableEntries = new HashSet<TimetableEntry>();
        }
    [Key]
        public int Subject_id { get; set; }
        public string Name { get; set; }
        public string code { get; set; }
        public bool no_exams { get; set; }
        public int max_weekily_classes { get; set; }
        public bool is_deleted { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public decimal credit_hours { get; set; }
        public bool prefer_consecutive { get; set; }
        public decimal amount { get; set; }
        public int Fk_Elective_Group_id { get; set; }
        public int Fk_Batch_id { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual ICollection<EmployeesSubject> EmployeesSubjects { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
        public virtual ICollection<FaGroupsSubject> FaGroupsSubjects { get; set; }
        public virtual ICollection<SubjectLeave> SubjectLeaves { get; set; }
        public virtual ICollection<TimetableEntry> TimetableEntries { get; set; }
    }
}
