//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public Timetable()
        {
            this.TimetableEntries = new HashSet<TimetableEntry>();
        }
    [Key]
        public int Timetable_id { get; set; }
        public Nullable<System.DateTime> start_date_ { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public bool is_active { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<TimetableEntry> TimetableEntries { get; set; }
    }
}
