//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimetableEntry
    {
        public TimetableEntry()
        {
            this.Attendences = new HashSet<Attendence>();
        }
    [Key]
        public int Timetable_Entry_id { get; set; }
        public int Fk_Batch_id { get; set; }
        public int Fk_Week_Day_id { get; set; }
        public int Fk_Class_Timing_id { get; set; }
        public int Fk_Subject_id { get; set; }
        public int Fk_Employee_id { get; set; }
        public int Fk_timetable_id { get; set; }
    
        public virtual ICollection<Attendence> Attendences { get; set; }
        public virtual Batch Batch { get; set; }
        public virtual ClassTiming ClassTiming { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Timetable Timetable { get; set; }
        public virtual Week_Day Week_Day { get; set; }
    }
}
