//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Week_Day
    {
        public Week_Day()
        {
            this.TimetableEntries = new HashSet<TimetableEntry>();
        }
    [Key]
        public int Week_Day_id { get; set; }
        public string Name { get; set; }
        public string week_day1 { get; set; }
        public int sort_order { get; set; }
        public int day_of_week { get; set; }
        public bool is_deleted { get; set; }
        public int Fk_Batch_id { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual ICollection<TimetableEntry> TimetableEntries { get; set; }
    }
}
